### ISSUE TITLE
Minor improvements 

### ISSUE THREAD

**Issue by samayo** [samayo/bulletproof#107]
### Milestone for V5
---
- [x] add #119
- [x]  [Remove translation](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L91) it only makes the code more unreadable, and instead add a token to the error log, so i18n can be done externally 
- [x]  [Remove redundant code](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L159) if/else isn't necessary
```php
// instead of if/else ... cast error to bool
return (bool) $this->error; 
```
- [x]  [Move name generation to set name](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L325-L341) getters shouldn't set anything. something like this should work
```php
$this->name ? filter_var(..) ? uniqid(..)
```
- [ ]  [Refractor validator function](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L441-L469) this should give 9/10 quality score on scrutinizer

- [ ] Decide whether to keep image manipulation functions as per comment  #108 
- [ ] Investigate/add more security layer as per #103 
- [ ] add multiple upload instruction

**Comment by samayo** [comment]
working on this, if someone wants to collab just write here

**Comment by samayo** [comment]
no longer required
