### ISSUE TITLE
V3 - milestone

### ISSUE THREAD

**Issue by samayo** [samayo/bulletproof#62]
- [ ] `getMime()` should return in `image/type` format, and add `getExt()` to return only the `ext`  
- [x] add `exif` extension requirement in composer.json
- [x] fix travis issue with php version 5.3 requirement. 
- [x] refractor `upload()` method / the upload() method contains ~10 lines of variable to array assignment which can be handled with just two lines of codes, if used array_combine. 
- [x] decrease minimum image-pixel requirement to 2px (for image validation)
